
GET http://localhost:4400/api/v1/user/

###

// signup
POST http://localhost:4400/api/v1/user/signup
Content-Type: application/json

{
  "name": "Prince V",
  "email": "princevirtron@gmail.com",
  "password": "vbc12345"
}

// verify email
###
POST http://localhost:4400/api/v1/email_verification/verify
Content-Type: application/json

{
  "email": "princevirtron@gmail.com",
  "otp": "6104"
}

// login
###
POST http://localhost:4400/api/v1/user
Content-Type: application/json

{
  "email": "princevirtron@gmail.com",
  "password": "vbc12345"
}

###
GET http://localhost:4400/api/v1/user/private_data?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGEwNDI4YmZiZGI1ZGQ1MjAxNWJkYzkiLCJlbWFpbCI6InByaW5jZXZpcnRyb25AZ21haWwuY29tIiwiaWF0IjoxNjg4MjI0NDQ3LCJleHAiOjE2OTA4MTY0NDd9.E3fMNCRzKG4snOhpzhujxGkjAYRuNYf8ZbS8wck1rGk
Content-Type: application/json






