
// signup
POST http://localhost:4400/api/v1/user/signup
Content-Type: application/json

{
  "name": "Prince V",
  "email": "princevirtron@gmail.com",
  "password": "vbc12345"
}

// verify email
###
POST http://localhost:4400/api/v1/email_verification/verify
Content-Type: application/json

{
  "email": "princevirtron@gmail.com",
  "otp": "8211"
}

// login
###
POST http://localhost:4400/api/v1/user
Content-Type: application/json

{
  "email": "vincentcornelius489@gmail.com",
  "password": "vbc12345"
}

###
GET http://localhost:4400/api/v1/user/private_data?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2RiM2Q4ZDY4NjM1MDJmM2I2ZGRlMWUiLCJlbWFpbCI6InZpbmNlbnRjb3JuZWxpdXM0ODlAZ21haWwuY29tIiwiaWF0IjoxNjc1MzkwODczLCJleHAiOjE3MDEzMTA4NzN9._tn0zsn5puByeEnfBWnpMKwlD8-nZXRR_vllqbU7DNc
Content-Type: application/json






