
GET http://localhost:4400/api/v1/user/

###

// signup
POST http://localhost:4400/api/v1/user/signup
Content-Type: application/json

{
  "name": "Daddy V",
  "email": "vincentcornelius489@gmail.com",
  "password": "vbc12345"
}

// verify email
###
POST http://localhost:4400/api/v1/email_verification/verify
Content-Type: application/json

{
  "email": "vincentcornelius489@gmail.com",
  "otp": "2935"
}

// login
###
POST http://localhost:4400/api/v1/user
Content-Type: application/json

{
  "email": "vincentcornelius489@gmail.com",
  "password": "vbc12345"
}

###
GET http://localhost:4400/api/v1/user/private_data?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2Y0MmYwZTdlNDcwNjBjNGY2ZGY3OGUiLCJlbWFpbCI6InZpbmNlbnRjb3JuZWxpdXM0ODlAZ21haWwuY29tIiwiaWF0IjoxNjc2OTQ3NDQwLCJleHAiOjE3MDI4Njc0NDB9.JuGLTB37Rz-COymSYw5uRGj2wc5DcyXWz2JXIqTeIBM
Content-Type: application/json






